<?php

namespace App\Http\Requests\Teacher;

use Illuminate\Foundation\Http\FormRequest;

class UserAssignmentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'assignment_grade' => 'required',
            'assignment_lesson' => 'required',
            'section' => 'nullable',
            'assignment_students' => 'required_if:section,nullable',
        ];
    }

    public function messages()
    {
        return [
            'assignment_grade.required' => 'الصف مطلوب للتعيين',
            'assignment_lesson.required' => 'الدرس مطلوب للتعيين',
            'assignment_students.required' => 'تحديد الطلاب مطلوب للتعيين',
        ]; // TODO: Change the autogenerated stub
    }

}
