name: Deploy Arabic-Arabs App

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # تحديث الريموت ليستخدم رمز الوصول الشخصي
      - name: Update Git Remote to use Token
        run: git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/omarshaheen95/ABT-Arabic-Arabs.git

      # Add server to known hosts
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

      # Test SSH Connection with username and password
      - name: Test SSH Connection
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }} "echo Connection successful"

      # Deploy files to the server
      - name: Deploy to Server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }} "
            cd /home/omar/websites/arabic-arabs &&
            git pull origin master &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache &&
            php artisan queue:restart
            "

